### ISSUE TITLE
The issue of incorrect attribute names

### ISSUE THREAD

**Issue by MelanTech** [opacity-black/RGBT_toolkit#5]
Hello, first of all, thank you for being able to open source this evaluation tool.

When I am using your tool to evaluate the attributes of RGBT234 and RGBT210, I found that the radar plot displayed the attribute `SC`. However, after reviewing related papers, I found that these two datasets do not have the attribute `SC`, but rather the attribute `SV`. Is this an error?
﻿
I noticed that you are building version 2.0 of the code. Will this issue be fixed in the new version? In addition, will the new version add attribute evaluation for GTOT? I'm looking forward to your reply!

**Comment by opacity-black** [comment]
Yes, you have found a very valuable mistake, which comes from a different formulation in a few papers. To avoid any misunderstanding, I will remove this mistake in the new version. For GTOT, I will try to include an attribute evaluation.
Thanks for your contribution.



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "opacity-black/RGBT_toolkit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月2日(星期一) 上午10:48
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[opacity-black/RGBT_toolkit] The issue of incorrect attribute names (Issue #5)





 
Hello, first of all, thank you for being able to open source this evaluation tool.
 
When I am using your tool to evaluate the attributes of RGBT234 and RGBT210, I found that the radar plot displayed the attribute SC. However, after reviewing related papers, I found that these two datasets do not have the attribute SC, but rather the attribute SV. Is this an error?
 ﻿
 I noticed that you are building version 2.0 of the code. Will this issue be fixed in the new version? In addition, will the new version add attribute evaluation for GTOT? I'm looking forward to your reply!

**Comment by MelanTech** [comment]
Okay, thank you for your prompt reply. Looking forward to the release of the new version💕

**Comment by Guobinyuan** [comment]
Do you fix the mistack？When I use your code, It's still SC, not SV
